# Generated by Django 2.0.1 on 2019-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
