# Generated by Django 2.0.1 on 2019-04-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_formentry_child'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_forms', to='enrollment.Child')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_forms', to='forms.Form')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='forms',
            field=models.ManyToManyField(through='enrollment.TakenForm', to='forms.Form'),
        ),
    ]
