# Generated by Django 2.0.1 on 2019-04-17 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_formentry_child'),
        ('enrollment', '0003_auto_20190416_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='formentries',
        ),
        migrations.RemoveField(
            model_name='child',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='takenform',
            name='child',
        ),
        migrations.AddField(
            model_name='takenform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='formentries',
            field=models.ManyToManyField(through='enrollment.TakenForm', to='forms.FormEntry'),
        ),
        migrations.AddField(
            model_name='user',
            name='forms',
            field=models.ManyToManyField(through='enrollment.TakenForm', to='forms.Form'),
        ),
    ]
