# Generated by Django 2.0.1 on 2019-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='childname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
