# Generated by Django 2.0.1 on 2019-04-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formentry_childname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='childname',
        ),
    ]
