# Generated by Django 2.0.1 on 2019-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_formentry_childname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(max_length=1000, verbose_name='Label'),
        ),
    ]
