# Generated by Django 2.0.1 on 2019-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20190504_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Help text'),
        ),
    ]
